#!/bin/bash

numNets=$1

rm *.net

for ((i=0; i<$numNets; i++))
do
    echo $i.net
    ./buildCollatzNet
    mv collatz.net $i.net
done

../exe/combine collatz.train *.net
../exe/eval_samples collatz.train combined.net 
